### ISSUE TITLE
IMOD not found if version == 4.9.0

### ISSUE THREAD

**Issue by EuanPyle** [alisterburt/yet-another-imod-wrapper#1]
Found that in our default IMOD version (4.9.0) this wrapper will say it can't find IMOD: this is because 
batchruntomo --help 
is not a valid command in this version (but is in v4.10.18 which I've tried it on also). Maybe it's worth deleting the --help flag in imod_is_installed in utils.py as help is printed in both versions of IMOD without the flag.

**Comment by EuanPyle** [comment]
Just realised: This doesn't matter as this only works with the latest version of IMOD by the looks of it!

**Comment by alisterburt** [comment]
simplified installation check so that this fails more gracefully :)
